### ISSUE TITLE
"Multiple Entries With Same Key" in BlazeScalaWorkspaceImporter

### ISSUE THREAD

**Issue by danielhfrank** [bazelbuild/intellij#106]
Hello folks,

I recently grabbed the latest version of the Intellij with Bazel plugin, hoping to use it for a large scala project at work. After a bit of wrangling, when running bazel sync I encountered the following error:
```
Multiple entries with same key: libactivation_db076cb=libactivation_db076cb and libactivation_db076cb=libactivation_db076cb
java.lang.IllegalArgumentException: Multiple entries with same key: libactivation_db076cb=libactivation_db076cb and libactivation_db076cb=libactivation_db076cb
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295)
	at com.google.idea.blaze.scala.sync.importer.BlazeScalaWorkspaceImporter.importWorkspace(BlazeScalaWorkspaceImporter.java:94)
	at com.google.idea.blaze.scala.sync.BlazeScalaSyncPlugin.lambda$updateSyncState$0(BlazeScalaSyncPlugin.java:111)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:37)
	at com.google.idea.blaze.scala.sync.BlazeScalaSyncPlugin.updateSyncState(BlazeScalaSyncPlugin.java:107)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$doSyncProject$2(BlazeSyncTask.java:392)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.doSyncProject(BlazeSyncTask.java:387)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.syncProject(BlazeSyncTask.java:192)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.lambda$run$0(BlazeSyncTask.java:159)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:60)
	at com.google.idea.blaze.base.scope.Scope.root(Scope.java:52)
	at com.google.idea.blaze.base.sync.BlazeSyncTask.run(BlazeSyncTask.java:140)
	at com.google.idea.blaze.base.async.executor.BlazeExecutor$2.run(BlazeExecutor.java:99)
...
```
Now, I raise this as an issue in part because the relevant code lists a comment saying that duplicate dependencies are expected, and will be squashed down in the map. It may be that I'm misinterpreting the comment or the error message, but it does not appear to be doing what the comment said!

Anyway, I'm just reporting this since it seems unexpected, and in case anybody else runs into it. I'll be using something else for now; know you're all busy, and appreciate the hard work on this so far. 

Just as an FYI, there was another change that I had to apply in order to even get to this point. The aspect implementation was raising an error when dealing with targets of the `scrooge_scala_library` type. I applied [these changes](https://gist.github.com/danielhfrank/ed076ab87d9332af39c42e5225af7763), but couldn't find that file in this repo anywhere. I'm not sure that the changes I linked are the "right" fix for my problem, they just got me a little more progress.

Thanks again for your hard work!

**Comment by ittaiz** [comment]
Dan,
What version of rules_scala and Bazel are you using? Can you also
explicitly say which version of the plugin?
If not everything is from HEAD can you try with all three being latest?
Is it mac or Linux?

**Comment by danielhfrank** [comment]
Hi Ittai, sorry for omitting that. Version information was:

Bazel: 0.5.1
rules_scala: 1947a197f849738d926e609584cfda4ecf669bd9 and 2381281753a49b35fdbbfd64f81c60e58549a6c4 (same issue on both versions)

Plugin version: 2017.06.05 , as downloaded from https://plugins.jetbrains.com/plugin/8609-intellij-with-bazel . I did not attempt to build the plugin from source.
I was running on a mac.

Thanks!

**Comment by ittaiz** [comment]
I also hit this.
At least in my use-case it's related to `neverlink` and non `neverlink` targets in the same workspace.
https://github.com/bazelbuild/intellij/issues/97#issuecomment-320491290

**Comment by chaoren** [comment]
@ittaiz The stacktrace looks like a different problem than what I suggested during our meeting. This might be fixable on the plugin side.

**Comment by ittaiz** [comment]
Great!
Since I'm some lever the plugin doesn't care if it's never link or not right? That's more of a bazel concern

**Comment by ittaiz** [comment]
@chaoren are you indeed looking at fixing this from the plugin side?

**Comment by ittaiz** [comment]
@chaoren are you indeed looking at fixing this from the plugin side?

**Comment by chaoren** [comment]
@ittaiz Yes, but it would help if there's a project I can use to reproduce.

**Comment by ittaiz** [comment]
I think the project I linked to in the other ticket shows it.
I'm going on vacation so will have limited access to email and no access to
IDE.

**Comment by chaoren** [comment]
@ittaiz sorry, right after writing that comment I saw the sample project. I have a fix, and it should be available by the next release.

**Comment by ittaiz** [comment]
👍🏽 thanks

**Comment by chaoren** [comment]
> Just as an FYI, there was another change that I had to apply in order to even get to this point. The aspect implementation was raising an error when dealing with targets of the scrooge_scala_library type. I applied these changes, but couldn't find that file in this repo anywhere. I'm not sure that the changes I linked are the "right" fix for my problem, they just got me a little more progress.

Fixed this problem too.

**Comment by ittaiz** [comment]
Awesome! Once this is released we'll update the .bazeproject we ship with the project since we currently omit them from rules_scala's IntelliJ view

**Comment by ittaiz** [comment]
@chaoren there was a release 5 days ago but it doesn't solve the problem (from it's name I guess it was cut on August 1st). Any idea on when the next release will be public?
I'm now blocked on this (since we now have a concrete need for neverlink and adding it will remove intellij support)

**Comment by brendandouglas** [comment]
The next release will likely be uploaded around August 28-29th.

**Comment by ittaiz** [comment]
Thanks

**Comment by ittaiz** [comment]
Hi @brendandouglas any news about the release?

**Comment by brendandouglas** [comment]
We had some problems with our OSS tests in the last release, and skipped the upload to the repository.

We'll make sure it gets uploaded this release though, which should go up at the end of the week.

**Comment by brendandouglas** [comment]
A quick update -- we're currently planning to upload a version with this fix tomorrow, though if there are release issues it's possible it might be delayed until early next week.

**Comment by ittaiz** [comment]
Thanks for the update. Keeping my fingers crossed....

**Comment by brendandouglas** [comment]
We've uploaded another CLion version (https://plugins.jetbrains.com/plugin/9554-bazel).

It's blocked waiting for JetBrains approval. Note, it requires (and supports) CLion 2017.2.

In the meantime, you could try building from source (which is currently up to date).

**Comment by brendandouglas** [comment]
My mistake, the IntelliJ plugin is already available, so this should already be fixed.

Closing for now -- please reopen if there are further issues.
