### ISSUE TITLE
Executing test programs in the debugger include an extraneous "--gunit_color" flag

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [bazelbuild/intellij#131]
When dispatching a build configuration in the debugger, the execution appends an additional command-line parameter: `--gunit_color=no`.

If the test has `gflags` enabled and that particular flag hasn't been defined, the test fails on an unrecognized flag.

Environment:
Clion version: 2017.1.3
Bazel plugin version: 2017.07.05.0.2
Testing framework: googletest 1.7.0

NOTE:
The *build* of the target is appropriate (as indicated in the Bazel Console window).

```
Building debug binary
Command: /usr/local/bin/bazel build --tool_tag=ijwb:CLion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title -c dbg --experimental_build_event_binary_file=/tmp/intellij-bep-e035d149-5de7-4e35-ba92-2e74ef5e0fcb --noexperimental_build_event_binary_file_path_conversion -c dbg --copt=-g --strip=never -- //workspace/path1/path2/file_test
```

However, in the debugger's console, the test is executed as follows (with the indicated flag):

```
/home/user/.cache/bazel/_bazel_user/51eedac7fff3f03cf920e33cbe183a2e/execroot/workspace/bazel-out/clang-3.9-linux-dbg/bin/path1/path2/file_test --gunit_color=no
```

It is worth noting, when executing the same test *without* the debugger attached, then it simply executes  the following (as displayed in the *run* window):

```
/usr/local/bin/bazel test --tool_tag=ijwb:CLion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --runs_per_test=1 --flaky_test_attempts=1 --test_sharding_strategy=disabled --experimental_build_event_binary_file=/tmp/intellij-bep-9c4d9aa0-b22e-4066-a685-3d074b04857d --noexperimental_build_event_binary_file_path_conversion -c dbg -- //workspace/path1/path2/file_test
```

It is unclear what purpose this flag is *supposed* to serve and inclusion of gflags causes conflict with this flag. Is this a bug?

**Comment by brendandouglas** [comment]
Are you running a non-gunit test here? Also, which version of the Bazel plugin are you on? -- this behavior was slightly improved in the latest version.

The flag is there to support debugging gunit tests, and works around: https://youtrack.jetbrains.com/issue/CPP-10054

**Comment by SeanCurtis-TRI** [comment]
Sorry about that -- I've added add'l information to the original problem description.

**Comment by jwnimmer-tri** [comment]
From the CPP-10054 link, I could understand why the plug-in would want to add `–gtest_color=no` to the command line.  I don't understand why it is adding `--gunit_color=no`, though (N.B. `gunit` vs `gtest` distinction) at https://github.com/bazelbuild/intellij/blob/015973d885a258d9b3921e5c06572bb4e1b30045/clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java#L166-L170?

**Comment by brendandouglas** [comment]
Ah, that appears to be an internal-only googletest flag (gtest_color wouldn't work for internal users).

You could temporarily work around this by defining that flag. In the meantime, we'll fix it up for external users.

**Comment by Lucy-tri** [comment]
Is there a workaround for this in CLion?

**Comment by SeanCurtis-TRI** [comment]
It should be solved in master.  See:

https://github.com/RobotLocomotion/drake/blob/master/drake/common/test_utilities/drake_cc_googletest_main.cc#L14

**Comment by brendandouglas** [comment]
This is fixed in the latest release, though you'll need to upgrade to CLion 2017.2 to pick it up -- full version compatibility details are here: https://plugins.jetbrains.com/plugin/9554-bazel

**Comment by Lucy-tri** [comment]
@brendandouglas  I am still seeing this, as Sean described in the original description, running a debug test, that the test is executed with the flag gest_color, which is unrecognized. Running CLion 2017.2.3 and Bazel plugin 2017.12.04.0.2.

**Comment by jwnimmer-tri** [comment]
@Lucy-tri That's a different problem => #274.
