### ISSUE TITLE
Build is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by lberki** [bazelbuild/intellij#2194]
The commit that broke this is https://github.com/bazelbuild/bazel/commit/50013ddb3d3010d0559a7ddbb611b9caf06f73b8 .

The cause is that `proto_library` used to (erroneously) allow imports using `$REPO/$REPO_RELATIVE_PATH`, which is not the case anymore after that change.

**Comment by lberki** [comment]
I have an open pull request to fix this at https://github.com/bazelbuild/intellij/pull/2193, but strictly speaking, I can only tick one of the three boxes.

**Comment by or-shachar** [comment]
Reported in #2179 and fixed in #2181 ...

**Comment by vladmos** [comment]
A friendly ping, Intellij plugins are still broken with Bazel@HEAD: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1790

**Comment by c-parsons** [comment]
Another ping. IntelliJ remains broken at Bazel@HEAD CI, which means that downstream projects depending on IntelliJ are also broken.

The longer this breakage persists, the riskier it becomes for affected projects: Failures may hide other issues, as Bazel@HEAD continues to develop.

**Comment by alice-ks** [comment]
Thanks for notifying us and helping with the resolution. By now, the combination of all fixes we needed result in a green build again (e.g. the IntelliJ plugins are green in https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1857).
