### ISSUE TITLE
Find usages, Find & the 'Scroll to source' button do not work in generated code/imported libraries

### ISSUE THREAD

**Issue by BrentDouglas** [bazelbuild/intellij#252]
When looking at code that shows up under the 'External Libraries' part of the project tree (both maven deps and generated libs) these three features fail.

- Clicking on a class or method, right clicking and selecting 'Find usages' always reports that there are none.
- Opening the global Find window and searching in the Project or Project and Libraries scopes will not find anything within external libraries. Oddly enough, if you select a directory from within the External library (e.g. `/work/project-00/.blaze/libraries/dom4j-1.6.1-ijar_72672d22.jar!/org/dom4j/bean` the preview window will list all the hits, but then if you select 'Open in find window' it reports that nothing was found.
- If you open an External Library class and then click the 'Scroll to source' nothing happens, the project tree does not move.

Bazel plugin: 2018.01.29.0.2
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

**Comment by BrentDouglas** [comment]
I would like to qualify point 3, The scroll to source button does not work when the library has a source jar attached, when it is showing the decompiled actual jar the button functions as expected.

**Comment by brendandouglas** [comment]
This should be fixed in the release after next. We now actually attach source jars (rather than just redirecting to them on the fly). It means the IDE will have to index the source jars, which slows things down, but also means you'll get support for find usages, navigation, etc.

**Comment by brownry1986** [comment]
I am still seeing these issues. Is the fix targeted for a specific release?

Intellij version:
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018

Bazel plugin version:
v2018.12.03.0.2

**Comment by brownry1986** [comment]
I have recreated this in a sample project here: https://github.com/brownry1986/BazelIssues

The HelloWorld.java class file is generated from a genrule (genrule just copies HelloWorld.txt to HelloWorld.java). SampleMain.java calls a method in the HelloWorld class. From SampleMain.java I can use Go To -> Declaration to jump into the generated class in the source jar, however from the generated class trying Find Usages returns no results. In addition, clicking Scroll to Source does nothing and Find in Path does not text in the generated class.

**Comment by brendandouglas** [comment]
@brownry1986, that's a different problem, and one that we don't have a solution for.

We rely on generated java source being produced by rules which expose the 'java' or JavaInfo providers to skylark. Plain genrules don't do this.

To get references, usages, etc. working as expected, you'd need to replace any arbitrary genrules with custom rules that expose one of these java providers.

**Comment by brownry1986** [comment]
Clear. Thanks for the extra info, we'll give this a try!

**Comment by brownry1986** [comment]
@brendandouglas One follow-up to this; we are generating the source code via a genrule but then we are creating a java_library from the generated sources. Does the java_library rule not expose the source jar for indexing?

**Comment by joprice** [comment]
@brownry1986 did you get this to work? I'm having a similar problem with a genrule
