### ISSUE TITLE
C++ standard not set correctly

### ISSUE THREAD

**Issue by cstrahan** [bazelbuild/intellij#296]
I've imported the [envoy](https://github.com/envoyproxy/envoy) project, and I've found that IntelliJ can't find `make_unique` in the `std` namespace (i.e. `std::make_unique`):

> Can't resolve namespace member 'make_unique'

I'm assuming this is because IntelliJ doesn't know what C++ standard to use. Normally one would specify something like so in their `CMakeLists.txt` to use C++ 14:

```cmake
set(CMAKE_CXX_STANDARD 14)
```

However, adding a `CMakeLists.txt` to the root of the project doesn't convince IntelliJ to use the desired standard.

Here's where the envoy build system passes `-std=c++14`:

https://github.com/envoyproxy/envoy/blob/1039178c218db0c2fd2f85cbe8313ad2ceabee01/bazel/envoy_build_system.bzl#L15

Some questions:

* Should the Bazel plugin be configuring IntelliJ to use the right standard for each file? e.g. should the plugin configure IntelliJ to honor the `-std=c++14` from the envoy build system?
* Is there a known way to make IntelliJ use a given standard?

This is on CLion 2017.3.4 with the Bazel 2018.03.26.0.5 plugin, running on Ubuntu 17.10.

**Comment by jvoung** [comment]
In envoy, each cc_library independently has -std=... vs once in the crosstool. This code [1] needs to pick up those per-cc_library flags, and propagate it through. Right now, only a few things are picked up (-D, -I, ...). May need to be careful about bazel sync performance though. CLion executes the compiler with -d to have the compiler dump #defines corresponding to the cmdline flags (e.g., converting -std=c++14 to the appropriate __cplusplus value). If there are many unique flags, there will be many compiler runs.

One workaround is to specify the -std flag at the top level in the .bazelproject file, and re-run bazel sync:

build_flags:
  --cxxopt=-std=c++14

Of course, that could end up applying the cmdline flag to more cc_library targets than intended within envoy.

[1] https://github.com/bazelbuild/intellij/blob/3ae2ad5c5496e160771fd74bedc1f42304ecb214/base/src/com/google/idea/blaze/base/sync/aspects/IdeInfoFromProtobuf.java#L232

**Comment by jvoung** [comment]
This should be fixed in the next plugin release.

**Comment by slonka** [comment]
This is still happening with the version from https://github.com/bazelbuild/intellij/issues/494#issuecomment-498814006 / https://github.com/bazelbuild/intellij/files/3254199/clwb_bazel.zip 

![image](https://user-images.githubusercontent.com/2753650/59227266-3b423380-8bd5-11e9-9de5-916a3a8958c5.png)
