### ISSUE TITLE
Get all tests passing with --incompatible_disable_legacy_cc_provider for Bazel 0.25.0

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/intellij#527]
It seems that the intellij plugin will start breaking with the next Bazel release 0.25 because of an incompatible change (https://github.com/bazelbuild/bazel/issues/7036)

```
1) testCoptsPrefinedMakeVars(com.google.idea.blaze.aspect.cpp.coptsmakevars.CoptsMakeVarsTest)
--
  | java.lang.AssertionError: The subject was expected to be true, but was false
  | at com.google.idea.blaze.aspect.cpp.coptsmakevars.CoptsMakeVarsTest.testCoptsPrefinedMakeVars(CoptsMakeVarsTest.java:37)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  | at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  | at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  | at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  | at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  | at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  | at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  | at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  | at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  | at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  | at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  | at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  | at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  | at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
  | at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  | at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  | at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
  | at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
  | at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
  | Caused by: java.lang.AssertionError: The subject was expected to be true, but was false
  | at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
  | at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
  | at com.google.common.truth.Subject.failWithRawMessage(Subject.java:423)
  | at com.google.common.truth.BooleanSubject.isTrue(BooleanSubject.java:35)
  | ... 24 more
```
As a summary, the old legacy provider cc will not be available anymore, you would need to use CcInfo. For more information on how to proceed, see [here](https://github.com/bazelbuild/bazel/issues/7036). If you have any questions, please let me know.

**Comment by brendandouglas** [comment]
Is this change being made internally as well? (if so, that sounds much more serious, and we should probably move discussion elsewhere)

**Comment by brendandouglas** [comment]
Fixed upstream, though it won't make it to the released bazel plugin until March 29th.

**Comment by oquenchil** [comment]
Hey Brendan, is the change exported to GitHub? Unfortunately, this is still showing up as a failure in our CI:

1) testCcBinary(com.google.idea.blaze.aspect.cpp.ccbinary.CcBinaryTest)
--
  | java.lang.AssertionError: The subject was expected to be true, but was false
  | at com.google.idea.blaze.aspect.cpp.ccbinary.CcBinaryTest.testCcBinary(CcBinaryTest.java:37)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  | at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  | at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  | at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  | at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  | at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  | at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  | at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  | at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  | at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  | at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  | at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  | at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  | at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
  | at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  | at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  | at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
  | at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
  | at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
  | Caused by: java.lang.AssertionError: The subject was expected to be true, but was false
  | at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
  | at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
  | at com.google.common.truth.Subject.failWithRawMessage(Subject.java:423)
  | at com.google.common.truth.BooleanSubject.isTrue(BooleanSubject.java:35)
  | ... 24 more
  |  
  | FAILURES!!!
  | Tests run: 1,  Failures: 1

**Comment by brendandouglas** [comment]
The pull request merging these changes (https://github.com/bazelbuild/intellij/pull/520) is currently blocked on some failing android studio tests.

I'm looking into a fix now.
