### ISSUE TITLE
Issue with Path-Escaping Using Intelli-J / Bazel on Mac

### ISSUE THREAD

**Issue by andponlin-canva** [bazelbuild/intellij#6316]
### Description of the bug:

When I am partial syncing a Java Bazel module I get the following error on a MacOS computer;

```
no such package '@@intellij_aspect//': The repository's path is "intellij_aspect" (absolute: "/Users/xyz/Library/Application") but it does not exist or is not a directory.
```

The problem is that the path contains a space on the Mac; the directory component is `Application Support`.

To solve this, you need to escape the path in the class at `src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java` in the method `getAspectRepositoryOverrideFlag`;

```
return OVERRIDE_REPOSITORY_FLAG + "=\"" + findAspectDirectory().getPath() + "\"";
```

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Partial sync a Java project on a Mac machine with Intelli-J installed into the default location.

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-233.15026.9, built on March 21, 2024

### What programming languages and tools are you using? Please provide specific versions.

Multiple, but Java in this case.

### What Bazel plugin version are you using?

2024.02.27.0.1-api-version-233

**Comment by muldrik** [comment]
@mai93 Hi, I see [this commit](https://github.com/bazelbuild/intellij/commit/75df98d20567ea012f0e4861e04254136534b44c) in the timeline but it's not attached to any branch. 
Could you explain why you abandoned it? Does it fix the issue?

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/1bf174ad8e5536e312e200f1fdb7bf30fd223a85

**Comment by BlackReloaded** [comment]
Hi, it seems the fix was reverted in [932b3f](https://github.com/tpasternak/bazel-intellij/commit/932b3f7cdbfac261a42be892ae3bd2f49f7e388a).

The Problem still exists, is there any other solution?

**Comment by tpasternak** [comment]
hey @BlackReloaded can you please share the plugin version, the bazel version, and (ideally) the `bazel build` command executed by the plugin?

**Comment by BlackReloaded** [comment]
Sure here are the values.

IDEA Version: Build #IU-243.21565.193
Plugin Version: 2024.11.19.0.1-api-version-243
Bazel Version: 7.4.1
Bazelisk Version: 1.19.0

Bazel Command: 
```
bazel info --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no "--override_repository=intellij_aspect=/Users/xxx/Library/Application Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect" --override_repository=intellij_aspect_template=/Users/xxx/src/myopenfactory/myopenfactory/.ijwb/.idea/aspect bazel-bin bazel-genfiles bazel-testlogs execution_root package_path output_path output_base release starlark-semantics java-home --
```

Error Output:
```
ERROR: unknown key(s): 'Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect'
```

**Comment by tpasternak** [comment]
oh, what shell you use?

**Comment by tpasternak** [comment]
so for some reson the quote marks (`"`) don't work correctly

**Comment by BlackReloaded** [comment]
I have test the escaping, if i run the command by hand and escape the space with a backslash, it also didn't work. I think this is more a bazel problem than from the plugin itself.

**Comment by tpasternak** [comment]
Well my guess there's something wrong with the shell config

**Comment by andponlin-canva** [comment]
Hello @BlackReloaded 👋  I've just tried this here with the same setup; Bazel 7.4.1, IDE 243, Plugin 2024.11.19.0.1 on a recent Mac with the same shell version as you and it seems to be working OK. Did the problem start after a recent upgrade of some sort?

**Comment by BlackReloaded** [comment]
>Did the problem start after a recent upgrade of some sort?

Yes, i have tried to downgrade the IDE but now i get the error in all Versions. I also have tried to downgrade the plugin to see if this would fix the problem i could't find any working versions :-(

I have tried some command to reproduce the escape error with other commands, but i do not get it, see:
```zsh
$ ls /Users/xxx/Library/Application Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect
ls: /Users/xxx/Library/Application: No such file or directory
ls: Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect: No such file or directory
```
This doesn't work as expected.
```zsh
$ ls /Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect
BUILD.bazel                    build_dependencies.bzl         intellij_info.bzl              make_variables.bzl
WORKSPACE                      build_dependencies_deps.bzl    intellij_info_bundled.bzl      tools
artifacts.bzl                  fast_build_info_bundled.bzl    intellij_info_impl_bundled.bzl
build_compose_dependencies.bzl flag_hack.bzl                  java_classpath.bzl
```
This works as expected.

```zsh
$  bazel info --override_repository=intellij_aspect=/Users/xxx/Library/Application\ Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect
ERROR: unknown key(s): 'Support/JetBrains/IntelliJIdea2024.3/plugins/ijwb/aspect'
```
But this doesn't work.
