### ISSUE TITLE
Sync fails with no such package '@@intellij_aspect//'.

### ISSUE THREAD

**Issue by kitbuilder587** [bazelbuild/intellij#6705]
### Description of the bug:

When I try to sync my project on new beta version of plugin, it fails with:
```
WARNING: errors encountered while analyzing target 'xxx', it will not be built.
no such package '@@intellij_aspect//': The repository's path is "intellij_aspect" (absolute: "/Users/zajdelovm/Library/Application Support/JetBrains/IdeaIC2024.2/plugins/ijwb_bazel.jar/aspect") but it does not exist or is not a directory.
```
When run it on previous versions of plugin it is completes with ok.

### Which Intellij IDE are you using? Please provide the specific version.

idea 2024.2

### What Bazel plugin version are you using?

2024.08.27.0.1-api-version-242

**Comment by tpasternak** [comment]
I can't reproduce that. Could you please try to uninstall and install plugin again?

**Comment by c16a** [comment]
@tpasternak Reinstalling the plugin doesn't help.

**Comment by tpasternak** [comment]
Hi, can you please share?
1. Plugin version
2. Channel (stable/beta)
3. IntelliJ Version
4. the result of `bazel info release`

**Comment by c16a** [comment]
This has been fixed in https://github.com/bazelbuild/intellij/releases/tag/v2024.12.03-stable

**Comment by taekahn** [comment]
Any chance this fix can be back-ported for CLion 2024.1.6 as well?
I'm using 2024.11.05.0.3-api-version-241 and getting this exact same error.

**Comment by jastice** [comment]
probably obsolete? please reopen in case it still reproduces
