### ISSUE TITLE
Repository '@@intellij_aspect' is not defined

### ISSUE THREAD

**Issue by dhruvilshah3** [bazelbuild/intellij#7204]
#### Description of the issue. Please be specific.
When building a project, I am running into the following error:

```
ERROR: Unable to find package for @@intellij_aspect//:intellij_info_bundled.bzl: The repository '@@intellij_aspect' could not be resolved: Repository '@@intellij_aspect' is not defined.
```

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Building the project from IntelliJ fails

#### Version information
IdeaCommunity: 2024.3.1.1
Platform: Mac OS X 13.7.2
Bazel for IntelliJ plugin: 2024.12.03.0.1-api-version-243
Bazel: 7.4.0

**Comment by mai93** [comment]
can you share the build command that the plugin tries to run?

**Comment by gradients-rogo** [comment]
I'm encountering the same issue. The command looks something like this:
bazel build --tool_tag=ijwb:IDEA:ultimate --target_pattern_file /home/joeyhkim/Documents/.../.ijwb/targets/targets-11123095387424115210 --keep_going --color=yes --progress_in_terminal_title=no --inject_repository=intellij_aspect=/home/joeyhkim/.local/share/JetBrains/IntelliJIdea2024.3/ijwb/aspect --inject_repository=intellij_aspect_template=/home/joeyhkim/Documents/GitHub/.../.ijwb/.idea/aspect --inject_repository=intellij_aspect=/home/joeyhkim/.local/share/JetBrains/IntelliJIdea2024.3/ijwb/aspect --inject_repository=intellij_aspect_template=/home/joeyhkim/Documents/GitHub/.../.ijwb/.idea/aspect --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --output_groups=intellij-resolve-java-direct-deps,intellij-info-generic,intellij-info-java-direct-deps --build_event_binary_file=/tmp/intellij-bep-9c9f2f4d-d662-416b-aa7a-0ddd1b220bec --nobuild_event_binary_file_path_conversion --build_event_publish_all_actions --curses=no --

**Comment by gradients-rogo** [comment]
Manually adding these two flags to my build command fixes the issue:

--override_repository=intellij_aspect=/home/joeyhkim/.local/share/JetBrains/IntelliJIdea2024.3/ijwb/aspect
--override_repository=intellij_aspect_template=/home/joeyhkim/Documents/.../.ijwb/.idea/aspect

**Comment by gradients-rogo** [comment]
Rolling the plugin back to [2024.11.19.0.2-api-version-243](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/stable/644968) fixes the issue for me.

**Comment by mai93** [comment]
@gradients-rogo was it also on mac? What version of Bazel are you using?

**Comment by vlnikolaiev** [comment]
I have the same issue with bazel of 8.0.0 version

**Comment by gradients-rogo** [comment]
I'm on Ubuntu 24.04

**Comment by ThomasGreenhill** [comment]
I have also been experiencing this issue, and reverting to an older version of the plugin did not resolve the issue. I am on:
Ubuntu 24.04
Bazel version 8.0.0 
CLion version 2024.3.1.1
Bazel for CLion 2024.12.17.0-api-version-243

**Comment by ThomasGreenhill** [comment]
Does anyone have a fix?

**Comment by gradients-rogo** [comment]
Rolling back to a previous version of the plugin and turning of bzlmod entirely by adding the following to my .bazelrc worked for me:

common --enable_workspace --noenable_bzlmod

**Comment by ujohnny** [comment]
Folks, my apologies for being quite here for some time. We're working on a fix for this one that also addresses several other issues (#7202), so it require some extra time to integrate the change. I'd recommend to remove `<idea.system.path>/blaze/projects/<your_project>` while IJ/CLion is closed and re-sync the project once the IDE is opened, that should work as a workaround.

**Comment by LeFrosch** [comment]
Should be fixed by #7202. If not feel free to reopen the issue and tag me.

**Comment by ThomasGreenhill** [comment]
Thanks @LeFrosch, that solves the issue I've been having for the last few weeks :)

**Comment by Algomorph** [comment]
Issue still occurs in CLion:
CLion 2024.3.2
com.google.idea.bazel.clwb (2025.01.07.0.1-api-version-243)

So far occurs on trying to sync any C++ target in the [gRPC project](https://github.com/grpc/grpc).

```
ERROR: Unable to find package for @@intellij_aspect//:intellij_info_bundled.bzl: The repository '@@intellij_aspect' could not be resolved: Repository '@@intellij_aspect' is not defined.
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
WARNING: errors encountered while analyzing target '//examples/cpp/route_guide:route_guide_callback_server', it will not be built.
Unable to find package for @@intellij_aspect//:intellij_info_bundled.bzl: The repository '@@intellij_aspect' could not be resolved: Repository '@@intellij_aspect' is not defined.
```

@LeFrosch please reopen

**Comment by LeFrosch** [comment]
@Algomorph Sorry for the inconvenience, I assume the fix is still only included in the beta build https://github.com/bazelbuild/intellij/pull/7233. See the readme for instruction on how to join the beta.

**Comment by taekahn** [comment]
Hi.
This still plagues 2024.1.6. plugin 2024.11.05.0.3-api-version-241

I understand this was fixed for main, but is this going to be back-ported for those of us using older versions of clion?

I have EAP, Beta, alpha, and  nightly released turned on, hoping to get a fix for this.


Thanks.

**Comment by LeFrosch** [comment]
I apologize for the inconvenience, but this will probably not be back ported to anything below 2024.2. Is there any reason you are not upgrading to 2024.2+ ?

**Comment by taekahn** [comment]
I must admit I find this a bit of an odd question, as I imagine many people
are on what they are on. It is, after all, a paid product that people may
or may not upgrade based on means and needs. At the end of the day, my
fallback license version is on 2024.1.
It’s a shame it won’t be supported, but it is what it.

**Comment by LeFrosch** [comment]
We don't plan to release any more updates for CLion 2024.1. In general, if you'd like to receive all recent product improvements, you need to have an active subscription.
