### ISSUE TITLE
v2019.05.13.0.2 is incompatible with Bazel 0.27's breaking changes

### ISSUE THREAD

**Issue by jin** [bazelbuild/intellij#931]
Example error:

```
ERROR: /Users/jingwen/bazels/github/src/test/cpp/util/BUILD:147:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_library rule //src/test/cpp/util:test_util: 
Traceback (most recent call last):
	File "/Users/jingwen/bazels/github/src/test/cpp/util/BUILD", line 147
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_jingwen/6387d55354406beb34e2bb3e2911dd1e/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_jingwen/6387d55354406beb34e2bb3e2911dd1e/external/intellij_aspect/intellij_info_impl.bzl", line 882, in intellij_info_aspect_impl
		collect_cpp_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/private/var/tmp/_bazel_jingwen/6387d55354406beb34e2bb3e2911dd1e/external/intellij_aspect/intellij_info_impl.bzl", line 387, in collect_cpp_info
		artifacts_from_target_list_attr(ctx, "hdrs")
	File "/private/var/tmp/_bazel_jingwen/6387d55354406beb34e2bb3e2911dd1e/external/intellij_aspect/artifacts.bzl", line 14, in artifacts_from_target_list_attr
		[artifact_location(f) for target in getattr(ctx.rule.attr, attr_name, []) for f in target.files]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

Fix is https://github.com/bazelbuild/intellij/commit/9e11bb331da07834b2dc31bb5118ef3c23151398 but it isn't rolled into v2019.05.13.0.2.

Working on a manual push for the latest cut.

**Comment by jin** [comment]
Plugins pushed, pending JetBrains approval.

**Comment by dieseldesai** [comment]
There's (at least) 1 more spot where this error appears:

File ".../external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File ".../external/intellij_aspect/intellij_info_impl.bzl", line 885, in intellij_info_aspect_impl
		collect_go_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File ".../external/intellij_aspect/intellij_info_impl.bzl", line 330, in collect_go_info
		[f for src in getattr(ctx.rule.attr, "srcs", []) for f in src.files]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.

**Comment by jin** [comment]
All instances of this error were fixed in https://github.com/bazelbuild/intellij/commit/9e11bb331da07834b2dc31bb5118ef3c23151398, which is in the pending plugin release.

**Comment by jin** [comment]
https://plugins.jetbrains.com/plugin/8609-bazel/update/64388 Is released. Please update to plugin 2019.06.03 if you're using Bazel 0.27.

**Comment by zhzhxtrrk** [comment]
this issue is not fixed perfectly, with this fix, java projects works happily, but golang projects still fails to sync.

Example error:
```
Traceback (most recent call last):
	File "/Users/zhzhxtrrk/Workspace/ws/tower/backend/gateway/reporter/BUILD.bazel", line 3
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_zhzhxtrrk/aca8b3a397226c3bd3d17fc1b6b4f05f/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_zhzhxtrrk/aca8b3a397226c3bd3d17fc1b6b4f05f/external/intellij_aspect/intellij_info_impl.bzl", line 887, in intellij_info_aspect_impl
		collect_go_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/private/var/tmp/_bazel_zhzhxtrrk/aca8b3a397226c3bd3d17fc1b6b4f05f/external/intellij_aspect/intellij_info_impl.bzl", line 331, in collect_go_info
		[f for src in getattr(ctx.rule.attr, "srcs", []) for f in src.files]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
INFO: Analyzed 6 targets (1 packages loaded, 9 targets configured).
```

**Comment by brendandouglas** [comment]
Thanks, we've just had internal reports of this as well (it was a regression in the latest release).

The root cause is that neither this github project's CI or our internal CI detect this (our internal version of bazel doesn't have this incompatible change). We'll look into fixing both sets of CI, as well as the actual regression for projects with golang targets.

**Comment by jin** [comment]
The golang code path is fixed by https://github.com/bazelbuild/intellij/commit/cbe1c6da43a43a23c9de4fb4a688ba276365a6ac.

**Comment by rharter** [comment]
Looks like this is also broken [here](https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L118) for Android projects.

**Comment by jin** [comment]
@rharter thanks for the report, I'm submitting a fix.
